// <auto-generated />
using System;
using Ingatlan_back_end;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ingatlan_back_end.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Ingatlan_back_end.Models.IngatlanModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<uint>("Ar")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("HirdetesDatuma")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("KategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("KepUrl")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Leiras")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("Tehermentes")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("KategoriaId");

                    b.ToTable("ingatlanok");
                });

            modelBuilder.Entity("Ingatlan_back_end.Models.KategoriaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("Nev")
                        .IsUnique();

                    b.ToTable("kategoriak");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nev = "Ház"
                        },
                        new
                        {
                            Id = 2,
                            Nev = "Lakás"
                        },
                        new
                        {
                            Id = 3,
                            Nev = "Építési telek"
                        },
                        new
                        {
                            Id = 4,
                            Nev = "Garázs"
                        },
                        new
                        {
                            Id = 5,
                            Nev = "Mezőgazdasági terület"
                        },
                        new
                        {
                            Id = 6,
                            Nev = "Ipari ingatlan"
                        });
                });

            modelBuilder.Entity("Ingatlan_back_end.Models.IngatlanModel", b =>
                {
                    b.HasOne("Ingatlan_back_end.Models.KategoriaModel", "Kategoria")
                        .WithMany()
                        .HasForeignKey("KategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
